/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AVG_H_RPCGEN
#define _AVG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 20

struct input_data {
	double list[200];
	int no_of_elements;
};
typedef struct input_data input_data;


#define PROGAVG 12345
#define VERAVG 1

#if defined(__STDC__) || defined(__cplusplus)
#define avg 1
extern  double * avg_1(input_data *, CLIENT *);
extern  double * avg_1_svc(input_data *, struct svc_req *);
extern int progavg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define avg 1
extern  double * avg_1();
extern  double * avg_1_svc();
extern int progavg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_data (XDR *, input_data*);
extern  bool_t xdr_input_data (XDR *, input_data*);

#else /* K&R C */
extern bool_t xdr_input_data ();
extern bool_t xdr_input_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AVG_H_RPCGEN */
